# Generated by Django 4.1.1 on 2022-09-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('study_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='teacher',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
