# Generated by Django 4.1.1 on 2022-09-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('learner', '0002_rename_lec_taken_learner_lectures_and_more'),
        ('study_session', '0002_alter_studysession_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='learner.learner'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
