# Generated by Django 4.1.1 on 2022-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='lec_taken',
            new_name='lectures',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='lec_given',
        ),
        migrations.AlterField(
            model_name='learner',
            name='qualification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learner',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
